name: CI

on: [push, pull_request]

jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Запуск Ruff
      run: ruff check
  App-testing:
      name: Tests
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Python installation
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3
      - name: Dependencies installation
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Testing app
        run: |
          pytest